development:
  secret_key_base: 1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef

test:
  secret_key_base: 1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
